#ifndef CONFIG_H
#define CONFIG_H

#define CFG_INPUT_MAX 80
#define CFG_WORD_MAX  16

#define CFG_ROOM_MAX  16
#define CFG_NAME_MAX  24
#define CFG_DESC_MAX  128

#define CFG_DIR_MAX   4

#define WORLD_ROOM_CAMP 0
#define WORLD_ROOM_ROAD 1
#define WORLD_ROOM_POND 2
#define WORLD_ROOM_FOREST 3
#define WORLD_ROOM_RUINS 4
#define WORLD_ROOM_STREAM 5
#define WORLD_ROOM_CLIFF 6
#define WORLD_ROOM_MARSH 7
#define WORLD_ROOM_GROVE 8
#define WORLD_ROOM_BRIDGE 9
#define WORLD_ROOM_CATACOMBS 10
#define WORLD_ROOM_MEADOW 11

#endif
